# -*- coding: utf-8 -*-
"""DSC 288 Reddit Scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSve6S6Ql_B-pYh2AbB7l1Eg8us1xtHX

# Accessing Reddit API
"""

#client ID 0vVkHqr-OpTLAuByKyuRFQ
#client secret uzND0brhnpyk31r8s142MxdOVkm1eg
#used https://pagenotfound.online/reddit-content-idea-mining-with-python/
  #https://asyncpraw.readthedocs.io/en/stable/code_overview/models/submission.html
!pip install asyncpraw
import asyncpraw
import pandas as pd

reddit = asyncpraw.Reddit(
    client_id="0vVkHqr-OpTLAuByKyuRFQ",
    client_secret="uzND0brhnpyk31r8s142MxdOVkm1eg",
    user_agent="DSC 288 Capstone (by u/TGM)",
)

top_posts = {'Title':[],'Text':[], 'Score':[]}
subreddit = await reddit.subreddit("dbtselfhelp") #999 rows
#subreddit = await reddit.subreddit("CBTpractice") #546 rows
async for submission in subreddit.top(time_filter="all",limit=None):
  top_posts["Title"].append(submission.title)
  top_posts["Text"].append(submission.selftext)
  top_posts["Score"].append(submission.score)

red_df = pd.DataFrame.from_dict(top_posts)
print(red_df)

temp_df = red_df[red_df['Text'] != '']

print(temp_df)

"""# Saving Topics to CSV"""

#Anger: r/Anger, r/AskReddit

#Anxiety: r/Anxiety, r/socialanxiety

#Assertiveness

#Bipolar: r/bipolar, r/BipolarReddit, r/BipolarSOs, r/bipolar2

#DBT/CBT: r/dbtselfhelp, r/CBT

#Depression: r/depression, r/depression_help

#Eating Disorder: r/EatingDisorders, r/EDAnonymous

#Panic: r/PanicAttack, r/panicdisorder

#Perfectionism

#Procrastination

#Self Esteem

#Topics:

#Anger
#Anxiety
#Bipolar
#Depression
#Eating Disorder
#Panic

#Others excluded because not large enough communities found or because DBT/CBT is more of a therapy style than topic

ang_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("Anger")
async for submission in subreddit.top(time_filter="all",limit=None):
  ang_posts["Title"].append(submission.title)
  ang_posts["Text"].append(submission.selftext)
  ang_posts["Score"].append(submission.score)
  ang_posts["Topic"].append("anger")

ang_df = pd.DataFrame.from_dict(ang_posts)
print(ang_df)

anx_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("Anxiety+socialanxiety")
async for submission in subreddit.top(time_filter="all",limit=None):
  anx_posts["Title"].append(submission.title)
  anx_posts["Text"].append(submission.selftext)
  anx_posts["Score"].append(submission.score)
  anx_posts["Topic"].append("anxiety")

anx_df = pd.DataFrame.from_dict(anx_posts)
print(anx_df)

bip_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("bipolar+BipolarReddit+BipolarSOs+bipolar2")
async for submission in subreddit.top(time_filter="all",limit=None):
  bip_posts["Title"].append(submission.title)
  bip_posts["Text"].append(submission.selftext)
  bip_posts["Score"].append(submission.score)
  bip_posts["Topic"].append("bipolar")

bip_df = pd.DataFrame.from_dict(bip_posts)
print(bip_df)

dep_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("depression+depression_help")
async for submission in subreddit.top(time_filter="all",limit=None):
  dep_posts["Title"].append(submission.title)
  dep_posts["Text"].append(submission.selftext)
  dep_posts["Score"].append(submission.score)
  dep_posts["Topic"].append("depression")

dep_df = pd.DataFrame.from_dict(dep_posts)
print(dep_df)

eat_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("EatingDisorders+EDAnonymous")
async for submission in subreddit.top(time_filter="all",limit=None):
  eat_posts["Title"].append(submission.title)
  eat_posts["Text"].append(submission.selftext)
  eat_posts["Score"].append(submission.score)
  eat_posts["Topic"].append("easting disorder")

eat_df = pd.DataFrame.from_dict(eat_posts)
print(eat_df)

pan_posts = {'Title':[],'Text':[], 'Score':[], 'Topic':[]}
subreddit = await reddit.subreddit("PanicAttack+panicdisorder")
async for submission in subreddit.top(time_filter="all",limit=None):
  pan_posts["Title"].append(submission.title)
  pan_posts["Text"].append(submission.selftext)
  pan_posts["Score"].append(submission.score)
  pan_posts["Topic"].append("panic")

pan_df = pd.DataFrame.from_dict(pan_posts)
print(pan_df)

raw_df = pd.concat([ang_df, anx_df, bip_df, dep_df, eat_df, pan_df])
print(raw_df)

raw_df.to_csv('DSC 288 Raw Reddit Dataset.csv', index=False)

